# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sneakersell' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sneakersell
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'JGProgressHUD'
pod 'IQKeyboardManagerSwift'
pod 'Kingfisher', '~> 5.0'

end
